name: CI/CD Pipeline for IRIS

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: steadfast-canto-473315-v8
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Docker image
      run: docker build -t us-central1-docker.pkg.dev/steadfast-canto-473315-v8/iris-repo/iris-app:latest .

    - name: Push Docker image
      run: docker push us-central1-docker.pkg.dev/steadfast-canto-473315-v8/iris-repo/iris-app:latest

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials iris-cluster --zone us-central1-a

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/autoscale.yaml

    - name: Stress Test using wrk
      run: |
        sudo apt-get install -y wrk
        EXTERNAL_IP=$(kubectl get svc iris-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "Testing $EXTERNAL_IP"
        wrk -t4 -c1000 -d30s http://$EXTERNAL_IP/
